version: '3.8'

services:
  # Servicio de MySQL
  db:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:   # ðŸ‘ˆ corregido: antes decÃ­a "enviroment"
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: abogado_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:   # ðŸ‘ˆ tambiÃ©n corregido
      PMA_HOST: db
      PMA_USER: root 
      PMA_PASSWORD: 12345
    ports:
      - "8080:80"
    depends_on:
      - db

  # Servicio de PHP + APACHE
  web:
    build: .
    container_name: php-web
    restart: always
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - "8000:80"
    entrypoint: ["sh", "-c", "sleep 15 && apache2-foreground"]

volumes:
  mysql_data:
